### ISSUE TITLE
Access Token errors if pop-up windows blocked by browser (chrome)

### ISSUE THREAD

**Issue by yankustefan** [pinoyyid/ngGAPI#7] opened 2015-04-09 01:27 UTC
Hi

I just played with the minimal.html example.

I have pop-up windows blocked  in Chrome (that open automatically).
Even if I open it, by clicking the "pop-up blocked" label, and give permission,
no files are listed.
After allowing pop-ups from my host, and refreshing the page, the warnings goes away.

If I do the same in Firefox, which also blocks the pop-up, the file list is populated,
after I manually open the pop-up and give permission.
So that works like expected.

I get the following warnings in my console. Infinitely repeating.

angular.min.js:102
[O75] refresh access token suppressed because there is already such a request in progress

nggapi_base.min.js:1
o88 gAT

I guess because the system is waiting for authentication.

**Comment by pinoyyid** [comment] 2015-04-09 04:57
Thanks for flagging this. I'm currently looking into a related issue where the same infinite loop appears after an OS suspend/sleep. I think the problem is that the gapi.auth.authorize function, instead of returning an error, simply never returns. 

I'll make two changes in the dev branch in the next hour or so.

1/ I'll put a timeout on waiting for the return which will cause the authorize to repeat (instead of looping O75 that there is an authorize in progress)

2/ I'll expose the refreshToken method so your app can manually call it in response to a user click. This is Google's recommended workaround as mentioned here https://developers.google.com/api-client-library/javascript/features/authentication#popup

**Comment by JohnnyEstilles** [comment] 2015-04-09 05:05
@pinoyyid I can confirm @yankustefan report. I experience the same issue on Chrome (Version 41.0.2272.118 (64-bit), on OS X), but not on FireFox or Safari. Haven't done any testing on Windows yet.

**Comment by yankustefan** [comment] 2015-04-09 05:11
@JohnnyEstilles Btw, I tested on windows.

**Comment by pinoyyid** [comment] 2015-04-09 08:18
I've just pushed 1897f01b115f1bf8a9cba468515e024d15a335e4 to the dev branch. It makes the following changes:-

* set a 10s timeout. If no auth or failure received in that time (prob due to blocked popup), displays an alert and retries
* communicate auth failures back to parent app. The most likely explanation would be a misconfigured app (eg. client ID or origin url), or the user has denied access. The app will receive a promise rejection with something like "401 no access token access_denied". Sadly the responses from gapi.auth are not documented by Google, so are liable to change.

Please let me know if these changes address your use case. 

As I mentioned previously, Google's "official" solution is to have the auth fired by a user action, eg a login button, which would not then be restricted by a popup blocker. This can be implemented in  ngGAPI by injecting the OauthService into your controller, and doing something like 
`<button ng-click="OauthService.refreshAccessToken()">Login</button>`

**Comment by yankustefan** [comment] 2015-04-09 09:09
Ok, Now I see an alert. Which helps the user to troubleshoot. Cool.

Not sure what you mean with "communicate auth failures back to parent app", but it sounds good.

Specially if it also enables us to display this errors/alerts in the UI of the app.
Also here a promise would maybe help to "communicate" the issue back to a controller. Then the developer could update some scope and update the template to show a warning within the UI. 

For example, this would enable the app developer to show a warning text (in place of the empty Google Drive file list) and maybe even expose a button as a fallback, so users can click it and don't have to worry how to un-block popups.

**Comment by pinoyyid** [comment] 2015-04-09 09:25
on the "communicate" bit, the approach ngGapi takes is to embed and automate OAuth so a beginner can pretty much ignore it. Thus an app such as minimal.html, simply calls 
`var responseObject = DriveService.files.list(); // where responseObject contains a .promise property`
and the OAuth is taken care of within the `list()`

The change I've made will communicate OAuth errors up through the responseObject promise, eg.

`responseObject.then(()=>{console.log('cool - here are your Drive files ', responseObject.data)} , (error)->{
if (error.indexOf('access_denied') > -1) {
  alert("sorry you chose not to authorise my app. Bye");
}
})`

The only caveat is that "access_denied" isn't guaranteed by Google to be stable. They do like to avoid documenting stuff, then changing stuff without telling anybody.

I think you raise an interesting use case where an app wants to do a more explicit auth phase rather than have it implicitly dealt with by the Drive methods. I think that's easy to do by injecting the OauthService and then calling the refreshToken and/or getAccessToken methods directly. I need to make a small change to refreshToken to return a promise.

**Comment by pinoyyid** [comment] 2015-04-09 10:29
on the blocked popups, I've just pushed a46c137d894af5a4c0f8d7fea388fd6699c0738a which adds 

`OauthServiceProvider.setPopupBlockedFunction(function (){
   console.error('popups blocked. Enable an Authorize button in the UI and toast the user, or display instructions on enabling popups')} );
`

This will override the default popup behaviour of displaying an alert.

I think that's about as far as we can go in dealing with popup blockers, so I'll close this issue.

**Closed by pinoyyid** 2015-04-09 10:29 UTC
